#!/usr/local/bin/ruby

require 'appscript'

itunes = Appscript.app("iTunes.app")

tracks = itunes.selection.get
tracks.each do |track|
  title = track.name.get
  path = track.location.get(:result_type => :alias)
  track.delete
  itunes.add(MacTypes::FileURL.path("#{path}"))
end


