#!/usr/local/bin/ruby

# March 14, 2012

require 'appscript'
require 'osax'

osax = OSAX.osax
texshop = Appscript.app("TeXShop")
sys_events = Appscript.app("System Events")

texshop.activate
path_re = /\/[A-Za-z0-9\- \/]*\//
file = texshop.document.path.get[0].gsub( /\.tex/, '.log')
filepath = MacTypes::Alias.path( file )
logfile = File.new( file, "r" ).readlines
cite_warning = /Citation `([A-Za-z]+_[A-Za-z]+[0-9]+[a-z]*)'/
cites_not_found = logfile.collect{ |line| cite_warning.match( line )[1] unless cite_warning.match( line ).nil? }.compact
if cites_not_found.empty? then
  osax.display_dialog( "No undefined citations.", 
    :buttons => ["OK"], 
    :default_button => 1, 
    :with_icon => :note )
else
  selection = osax.choose_from_list( cites_not_found, 
    :with_prompt => "#{cites_not_found.length} undefined Citations:" )
  if selection then
    texshop.activate
    sys_events.keystroke('f', :using => :command_down )
    sys_events.keystroke( selection[0] + "\r" )
  end
end