#!/usr/local/bin/ruby

# March 14, 2012

require 'appscript'

graphics_paths = ['', 'Figures/']

class String
  
  def is_eps?
    eps_re = /[A-Za-z0-9\-_]+.eps/
    if eps_re.match(self) then
      return true
    else
      return false
    end
  end
  
end

texshop = Appscript.app("TeXShop")
illustrator = Appscript.app("Adobe Illustrator")
illustrator.activate

# get filename from current TeXshop selection

path_re = /\/[A-Za-z0-9\- \/]*\//
file = texshop.document.path.get[0]
dir = path_re.match(file)
selection = texshop.document.selection.content.get[0]
filename = selection.is_eps? ? selection : selection + '.eps'

# check that this file exists in any directories listed in graphics_paths

valid_paths = graphics_paths.collect do |path|
   filepath = dir.to_s + path + filename
   File.exists?(filepath) ? filepath : nil
end.compact
abort("File not found") if valid_paths.empty?

filepath = MacTypes::Alias.path( valid_paths[0] )
begin
  illustrator.open( filepath )
rescue
  abort("Illustrator has failed to open #{filename}")
end