#!/usr/local/bin/ruby

# April 19, 2012

require 'appscript'
require 'osax'

finder = Appscript.app("Finder")
osax = OSAX.osax

sel = finder.selection.get(:result_type => :alias)
osax.set_the_clipboard_to( sel.map{ |path| path.path }.join("\n") )
