#!/usr/local/bin/ruby

# September 6, 2011

require 'appscript'
require 'osax'

def records # still hoping that Papers2 will become AppleScriptable
  $papers.activate
  $system_events.processes["Papers2"].menu_bars[1].menu_bar_items['Edit'].menus['Edit'].menu_items['Copy As'].menus['Copy As'].menu_items['BibTeX Record'].click 
  clipboard = OSAX.osax.the_clipboard
  return clipboard[0] == "%" ? clipboard.split("\r\r")[1..-1] : [ clipboard ]
end
    
$papers = Appscript.app("/Applications/Papers2.app")
bibdesk = Appscript.app("/Applications/BibDesk.app")

$system_events = Appscript.app("System Events.app")

library = "/Users/ben/Documents/My Papers/Bibliography.bib"

bibdesk.run unless bibdesk.is_running?
bibdesk.open(MacTypes::Alias.path( library ) ) unless bibdesk.documents.count > 0 
records.each{ |article| bibdesk.documents[1].import( :from => article ) }
bibdesk.activate