#!/usr/local/bin/ruby

# January 23, 2012

require 'osax'

osax = OSAX.osax

paper_title = osax.the_clipboard
project = "downloaded"
context = "reading"

begin
  command = "otask \"#{paper_title} @#{context} \##{project}\""
  reply = `#{command}`
rescue err
  reply = err
end
  
osax.display_dialog( reply, :buttons => ["OK"], :default_button => 1 )
