#!/opt/local/bin/ruby
# December 14, 2011

require 'appscript'
require 'osax'

numbers = Appscript.app("Numbers.app")
whose = Appscript.its

sheets = numbers.documents[1].sheets.get
to_paste = OSAX.osax.the_clipboard.split(/run[0-9]*/).delete_if { |array| 
  array == "" }.map { |array| 
  array.split(/[\r\n]/).delete_if { |element| element == "" } 
} # Content to be pasted should be separated by line breaks
number_of_entries = to_paste.length
number_of_sheets = to_paste[0].length
    
sheets.each do |sheet|
  sheet.tables.get.each do |table|
    begin
      $selection = table.selection_range.name.get.split(":")[0] # Not sure why $selection doesn't survive outside the do ; end loop unless it is global
    rescue
    end
  end
end

column = $selection.match(/[A-Z]+/).to_s
row = $selection.match(/\d+/).to_s.to_i

# Assume that n data entries are being pasted into identical cells across the first n sheets of the current document
(0...number_of_entries).each do |i|
  sheets[0...number_of_sheets].each_with_index do |sheet, index|
    sheet.tables[0].cells[ "#{column}#{row+i}" ].value.set( to_paste[i][index] )
    puts to_paste[i][index]
    # sheet.tables[0].cells[ $selection ].value.set( to_paste[index] )
  end
end