#!/usr/local/bin/ruby
# December 14, 2011

require 'appscript'
require 'osax'

numbers = Appscript.app("Numbers.app")
document = numbers.documents[1]
whose = Appscript.its

def get_focus_from( document ) # returns the string index of the currently selected cell (e.g. "B32")
  whose = Appscript.its
  selection_array = document.sheets.tables[whose.selection_range.name.eq(:missing_value).not].selection_range.name.get
  selection_array.delete_if{ |e| e.empty? }[0][0].split(":")[0]
end

sheets = document.sheets.get
to_paste = OSAX.osax.the_clipboard.split(/run[0-9]+[A-Za-z0-9 \-\._]+[\n\r]/).delete_if { |array| 
  array == "" }.map { |array| 
  array.split(/[\r\n]/).delete_if { |element| element == "" } 
} # Content to be pasted should be separated by line breaks
number_of_entries = to_paste.length
data_length = to_paste[0].length
number_of_sheets = document.sheets.name.get.delete_if{ |e| e =~ /[Pp]lot/ }.length
if data_length > number_of_sheets
  OSAX.osax.display_dialog("The number of data elements exceeds the number of valid sheets.", :with_icon => :caution, :buttons => "OK", :default_button => 1)
  exit
end


selection = get_focus_from(document)    
column = selection.match(/[A-Z]+/).to_s
row = selection.match(/\d+/).to_s.to_i

# Assume that n data entries are being pasted into identical cells across the first n sheets of the current document
(0...number_of_entries).each do |i|
  sheets[0...data_length].each_with_index do |sheet, index|
    sheet.tables[0].cells[ "#{column}#{row+i}" ].value.set( to_paste[i][index] )
    puts to_paste[i][index]
  end
end
